#!/usr/bin/env node
'use strict';

// Gathers real code and documentation already on this Mac for mx4's
// pretraining — nothing is downloaded: Python's standard library and
// installed packages, JavaScript from Node and npm, maxshell's own source
// and README, and the man pages (rendered to plain text). Files are
// cleaned (licence headers trimmed, minified and generated files skipped),
// exact duplicates dropped (Homebrew and the framework ship the same
// files), and long files split at blank lines into pieces of ~6000 chars.
//
//   node ai/mx4/collect.js   →  ai/mx4/data/pretrain.jsonl  {"src", "lang", "text"}

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { spawnSync } = require('child_process');

const OUT = path.join(__dirname, 'data');
const ROOT = path.join(__dirname, '..', '..');
const PY = '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13';

const SOURCES = [
  { name: 'python stdlib', dir: PY, ext: ['.py'], skip: /site-packages|\/test\/|\/tests\/|lib2to3|idlelib\/idle_test|__pycache__/, cap: 40e6 },
  { name: 'python packages', dir: path.join(PY, 'site-packages'), ext: ['.py'], skip: /\/tests?\/|__pycache__|_vendor|\/torch\/|\/sympy\/|\/numpy\/(core|_core)\/tests|benchmarks|\/babel\/locale/, cap: 90e6 },
  { name: 'homebrew python', dir: '/opt/homebrew', ext: ['.py'], skip: /\/tests?\/|__pycache__|site-packages\/(torch|numpy)|google-cloud-sdk|googlecloudsdk|\/surface\//, cap: 40e6 },
  { name: 'node + npm', dir: '/opt/homebrew/lib/node_modules', ext: ['.js', '.mjs', '.md'], skip: /\.min\.|\/dist\/|\/test\/|\/tests\/|maxshell/, cap: 15e6 },
  { name: 'node itself', dir: '/opt/homebrew/Cellar/node', ext: ['.js', '.mjs'], skip: /\.min\.|\/test\//, cap: 10e6 },
  { name: 'maxshell', dir: ROOT, ext: ['.js', '.md', '.py', '.sh', '.c'], skip: /node_modules|\/ai\/(data|mx\d\/data)|\/models\/|\.git\/|\/ai\/mx\d?\/?(code|knowledge)/, cap: 5e6 },
];

const LANG = { '.py': 'python', '.js': 'javascript', '.mjs': 'javascript', '.md': 'markdown', '.sh': 'bash', '.c': 'c', man: 'man' };

function* walk(dir, skip) {
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
  for (const e of entries) {
    const p = path.join(dir, e.name);
    if (skip && skip.test(p + (e.isDirectory() ? '/' : ''))) continue;
    if (e.isDirectory()) yield* walk(p, skip);
    else if (e.isFile()) yield p;
  }
}

// Drops a long licence block at the top (it's the same few texts over and
// over); keeps everything that's actually code.
function clean(text) {
  let t = text.replace(/\r\n/g, '\n').replace(/\t/g, '    ');
  const head = t.slice(0, 4000);
  const m = /^(?:#![^\n]*\n)?(?:(?:#[^\n]*\n)+|\/\*[\s\S]*?\*\/\n|"""[\s\S]*?"""\n)/.exec(head);
  if (m && /licen[sc]e|copyright/i.test(m[0]) && m[0].split('\n').length > 6) t = t.slice(m[0].length).replace(/^\n+/, '');
  return t.trim();
}

function usable(text) {
  if (text.length < 200) return false;
  const lines = text.split('\n');
  const long = lines.filter((l) => l.length > 300).length;
  if (long > 3 || long / lines.length > 0.02) return false; // minified or data
  if (/�/.test(text)) return false;
  if (/generated by|do not edit|autogenerated/i.test(text.slice(0, 600))) return false;
  const letters = (text.match(/[a-z]/gi) || []).length;
  return letters / text.length > 0.3;
}

// Pieces of about `size` characters, cut at blank lines.
function pieces(text, size = 6000) {
  if (text.length <= size * 1.3) return [text];
  const out = [];
  let cur = '';
  for (const block of text.split(/\n\n+/)) {
    if (cur && cur.length + block.length > size) { out.push(cur); cur = ''; }
    cur += (cur ? '\n\n' : '') + block;
    // Hard cuts move back off a surrogate pair, so emoji aren't split.
    while (cur.length > size * 2) { let at = size; if (/[\ud800-\udbff]/.test(cur[at - 1])) at--; out.push(cur.slice(0, at)); cur = cur.slice(at); }
  }
  if (cur.trim()) out.push(cur);
  return out;
}

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const file = path.join(OUT, 'pretrain.jsonl');
  const fd = fs.openSync(file, 'w');
  const seen = new Set();
  const totals = {};
  const write = (src, lang, text) => {
    for (const p of pieces(text)) {
      fs.writeSync(fd, `${JSON.stringify({ src, lang, text: p })}\n`);
      totals[src] = (totals[src] || 0) + p.length;
    }
  };
  for (const s of SOURCES) {
    let bytes = 0;
    for (const f of walk(s.dir, s.skip)) {
      if (bytes > s.cap) break;
      const ext = path.extname(f);
      if (!s.ext.includes(ext)) continue;
      let st;
      try { st = fs.statSync(f); } catch { continue; }
      if (st.size > 200000 || st.size < 200) continue;
      let text;
      try { text = clean(fs.readFileSync(f, 'utf8')); } catch { continue; }
      if (!usable(text)) continue;
      const h = crypto.createHash('sha1').update(text).digest('hex');
      if (seen.has(h)) continue;
      seen.add(h);
      // The file's path is a useful hint, as code is usually seen with one.
      const rel = f.replace(/^.*\/(site-packages|python3\.\d+|node_modules|lib)\//, '').replace(ROOT + '/', '');
      const lang = LANG[ext];
      write(s.name, lang, lang === 'markdown' ? text : `# ${rel}\n${text}`.replace(/^# /, lang === 'javascript' || lang === 'c' ? '// ' : '# '));
      bytes += text.length;
    }
  }
  // Man pages, rendered as you'd read them in the terminal.
  let manBytes = 0;
  for (const f of walk('/usr/share/man/man1')) {
    if (manBytes > 12e6) break;
    const r = spawnSync('mandoc', ['-T', 'utf8', f], { encoding: 'utf8', timeout: 5000, maxBuffer: 4e6 });
    if (r.status !== 0 || !r.stdout) continue;
    const text = r.stdout.replace(/.\x08/g, '').replace(/\n{3,}/g, '\n\n').trim();
    if (text.length < 300) continue;
    const h = crypto.createHash('sha1').update(text).digest('hex');
    if (seen.has(h)) continue;
    seen.add(h);
    write('man pages', 'man', text);
    manBytes += text.length;
  }
  fs.closeSync(fd);
  for (const [k, v] of Object.entries(totals)) process.stderr.write(`  ${k.padEnd(16)} ${(v / 1e6).toFixed(1)} MB\n`);
  process.stderr.write(`wrote ${(fs.statSync(file).size / 1e6).toFixed(1)} MB → ai/mx4/data/pretrain.jsonl\n`);
}

main();
