'use strict';

// How-to knowledge for mx: [ways to say the task…], answer. The dataset
// generator asks each one many ways ("how do I…", "can you tell me how to…",
// "steps to…"). Answers are short and practical, with steps where it helps.

module.exports = [
  // --- web browsers ------------------------------------------------------------
  [['open a new tab in a browser', 'open a new tab', 'make a new tab in a browser', 'make a new tab', 'open a new tab in chrome', 'open a new tab in safari'], 'Press ⌘T (Ctrl-T on Windows). You can also click the + next to your tabs.'],
  [['close a tab', 'close a browser tab'], 'Press ⌘W (Ctrl-W on Windows), or click the × on the tab.'],
  [['reopen a closed tab', 'get back a tab i closed', 'undo closing a tab'], 'Press ⌘⇧T (Ctrl-Shift-T on Windows). Press it again to bring back more tabs.'],
  [['open a new window in a browser', 'open a new browser window'], 'Press ⌘N (Ctrl-N on Windows).'],
  [['open a private window', 'go incognito', 'open an incognito window', 'browse privately'], 'In Chrome press ⌘⇧N; in Safari or Firefox press ⌘⇧P. (Ctrl instead of ⌘ on Windows.)'],
  [['switch between tabs', 'go to the next tab'], 'Press Ctrl-Tab for the next tab and Ctrl-Shift-Tab for the previous one. ⌘1 to ⌘9 jump to a tab by number.'],
  [['refresh a web page', 'reload a page', 'refresh the page'], 'Press ⌘R (F5 or Ctrl-R on Windows). ⌘⇧R reloads without the cache.'],
  [['find a word on a web page', 'search a web page', 'find text on a page'], 'Press ⌘F (Ctrl-F on Windows) and type the word. Enter jumps to the next match.'],
  [['zoom in on a web page', 'make a web page bigger', 'make the text bigger in a browser'], 'Press ⌘+ to zoom in, ⌘− to zoom out, and ⌘0 to reset (Ctrl on Windows).'],
  [['bookmark a page', 'save a website as a bookmark'], 'Press ⌘D (Ctrl-D on Windows) and choose where to save it.'],
  [['clear my browser history', 'delete my browsing history'], 'Press ⌘⇧⌫ in Chrome (Ctrl-Shift-Delete on Windows), or in Safari choose History → Clear History.'],
  [['go back to the last page', 'go back a page in a browser'], 'Press ⌘[ or ⌘← (Alt-← on Windows), or click the back arrow.'],
  [['make a browser full screen'], 'Press ⌃⌘F on a Mac, or F11 on Windows.'],
  [['download a file from a website', 'download something from a website'], 'Click the download link or button. The file goes to your Downloads folder — ⌥⌘L shows downloads in most browsers.'],
  [['change my homepage', 'set my homepage'], 'Open the browser’s Settings, find “On startup” or “Homepage”, and enter the page you want.'],
  [['copy a link', 'copy a website address', 'copy the url'], 'Click the address bar (or press ⌘L), then press ⌘C to copy it.'],

  // --- your Mac --------------------------------------------------------------------
  [['take a screenshot', 'screenshot my screen', 'take a screenshot on a mac'], 'Press ⌘⇧3 for the whole screen, ⌘⇧4 to drag a box, or ⌘⇧5 for more options. They go to your Desktop.'],
  [['take a screenshot of one window', 'screenshot a window'], 'Press ⌘⇧4, then Space, then click the window.'],
  [['force quit an app', 'close a frozen app', 'quit an app that is not responding'], 'Press ⌥⌘Esc, pick the app and click Force Quit.'],
  [['quit an app', 'close an app on a mac'], 'Press ⌘Q while the app is in front.'],
  [['switch between apps', 'switch apps'], 'Hold ⌘ and press Tab to cycle through open apps.'],
  [['copy and paste', 'copy paste', 'copy text'], 'Select it, press ⌘C to copy, then ⌘V to paste (Ctrl-C and Ctrl-V on Windows).'],
  [['cut and paste', 'move text'], 'Select it, press ⌘X to cut, then ⌘V to paste where you want it.'],
  [['undo something', 'undo a mistake', 'undo'], 'Press ⌘Z (Ctrl-Z on Windows). ⌘⇧Z redoes it.'],
  [['select all', 'select all the text'], 'Press ⌘A (Ctrl-A on Windows).'],
  [['make a new folder', 'create a folder', 'make a folder on a mac'], 'In Finder press ⌘⇧N, type a name and press Return. (In maxshell: `mkdir name`.)'],
  [['rename a file', 'change the name of a file'], 'Click the file once, press Return, type the new name and press Return again.'],
  [['delete a file', 'move a file to the trash'], 'Select it and press ⌘⌫ to move it to the Trash.'],
  [['empty the trash', 'empty the bin'], 'Right-click the Trash in the Dock and choose Empty Trash.'],
  [['find a file on my mac', 'search for a file', 'find a file'], 'Press ⌘Space to open Spotlight and type part of the name. (In maxshell: `files`, then f to search.)'],
  [['open spotlight', 'search my mac'], 'Press ⌘Space and start typing.'],
  [['type an emoji', 'add an emoji', 'use emojis on a mac'], 'Press Fn-E (or ⌃⌘Space) to open the emoji picker.'],
  [['turn on dark mode', 'use dark mode', 'make my mac dark'], 'Open System Settings → Appearance and choose Dark.'],
  [['change my wallpaper', 'change my desktop background', 'change my background'], 'Open System Settings → Wallpaper and pick a picture.'],
  [['connect to wifi', 'join a wifi network', 'connect to the internet'], 'Click the Wi-Fi icon in the menu bar and pick your network, then enter its password.'],
  [['turn on bluetooth', 'connect bluetooth headphones', 'pair bluetooth headphones'], 'Open System Settings → Bluetooth, turn it on, put the device in pairing mode and click Connect.'],
  [['check my battery', 'see my battery percentage'], 'Look at the battery icon in the menu bar; System Settings → Battery shows the percentage and health.'],
  [['check my storage', 'see how much space i have', 'check disk space'], 'Open  → About This Mac → More Info → Storage. (In maxshell: `df -h ~`.)'],
  [['uninstall an app', 'delete an app', 'remove an app'], 'Drag the app from Applications to the Trash, then empty the Trash.'],
  [['install an app', 'get an app on a mac'], 'Open the App Store, search for it and click Get. Or download it from the maker’s website and drag it into Applications.'],
  [['update my mac', 'update macos'], 'Open System Settings → General → Software Update.'],
  [['restart my mac', 'restart my computer'], 'Click  in the top-left corner and choose Restart.'],
  [['lock my screen', 'lock my mac'], 'Press ⌃⌘Q.'],
  [['split my screen', 'use split screen', 'put two windows side by side'], 'Hover over the green button in a window’s corner and choose Tile Window to Left or Right of Screen.'],
  [['make a window full screen'], 'Press ⌃⌘F, or click the green button in the window’s corner.'],
  [['minimize a window', 'hide a window'], 'Press ⌘M to minimize it, or ⌘H to hide the whole app.'],
  [['zip a file', 'compress a file', 'make a zip file'], 'Right-click it in Finder and choose Compress. (In maxshell: `zip -r archive.zip folder`.)'],
  [['unzip a file', 'open a zip file'], 'Double-click the .zip in Finder. (In maxshell: `unzip file.zip`.)'],
  [['record my screen', 'screen record'], 'Press ⌘⇧5 and choose Record Entire Screen or Record Selected Portion.'],
  [['airdrop a file', 'send a file with airdrop'], 'Right-click the file, choose Share → AirDrop, and pick the nearby device.'],
  [['change my mouse speed', 'change trackpad speed'], 'Open System Settings → Trackpad (or Mouse) and move the Tracking speed slider.'],
  [['see hidden files', 'show hidden files'], 'In Finder press ⌘⇧. (period). In maxshell: `ls -a`, or `.` inside `files`.'],
  [['open the terminal', 'open terminal'], 'Press ⌘Space, type Terminal and press Return.'],
  [['type faster', 'get better at typing'], 'Keep your fingers on the home row (ASDF JKL;), look at the screen instead of the keys, and practise a few minutes every day.'],

  // --- the terminal and shell ----------------------------------------------------------
  [['list files in a folder', 'see the files in a folder', 'list files'], 'Run `ls`. `ls -l` adds sizes and dates, and `ls -a` shows hidden files too.'],
  [['go into a folder', 'change folders in the terminal', 'change directory'], 'Run `cd folder-name`. `cd ..` goes up one folder and `cd` alone goes home.'],
  [['make a folder in the terminal', 'create a directory'], 'Run `mkdir name`. `mkdir -p a/b/c` makes several levels at once.'],
  [['make a new file in the terminal', 'create an empty file'], 'Run `touch name.txt`, or `edit name.txt` to create it and start writing.'],
  [['copy a file in the terminal', 'copy a file'], 'Run `cp source destination`. Add `-r` to copy a whole folder.'],
  [['move a file in the terminal', 'move a file'], 'Run `mv source destination`. The same command renames a file.'],
  [['delete a file in the terminal'], 'Run `rm file` — careful, it doesn’t go to the Trash. In maxshell, `files` then t moves things to the Trash instead.'],
  [['see what is inside a file', 'read a file in the terminal', 'print a file'], 'Run `cat file` for short files, or `view file` for long ones.'],
  [['search inside files', 'find text in files'], 'Run `grep -rn "text" .` to search every file under this folder.'],
  [['find a file in the terminal', 'find files by name'], 'Run `find . -name "*.txt"`, or `files` and press f.'],
  [['see running programs', 'see what is running', 'see running processes'], 'Run `top` for a live view, or `ps aux` for a list.'],
  [['stop a running command', 'cancel a command'], 'Press Ctrl-C.'],
  [['kill a program', 'kill a process'], 'Run `top`, select it and press k — or `kill PID` with its process number.'],
  [['see where i am in the terminal', 'print the current folder'], 'Run `pwd`. The prompt shows it too.'],
  [['clear the terminal', 'clear the screen'], 'Press Ctrl-L or type `clear`.'],
  [['see my command history', 'find an old command'], 'Press Ctrl-R and type part of it, or run `history`.'],
  [['make a command shortcut', 'make an alias'], 'Run `alias ll=\'ls -l\'`. Put it in ~/.maxshellrc to keep it.'],
  [['run a script', 'run a shell script'], 'Run `maxshell script.sh`, or make it executable with `chmod +x script.sh` and run `./script.sh`.'],
  [['make a file executable'], 'Run `chmod +x file`.'],
  [['check my internet connection', 'test my internet'], 'Run `ping -c 3 apple.com`. Replies mean you’re online.'],
  [['download a file in the terminal', 'download with curl'], 'Run `curl -LO https://example.com/file.zip`.'],
  [['install homebrew', 'get homebrew'], 'Follow the one-line install command on brew.sh, then run `brew install something`.'],
  [['install a program with homebrew', 'use brew'], 'Run `brew install name`, for example `brew install wget`.'],

  // --- git ----------------------------------------------------------------------------
  [['start a git repository', 'make a git repo', 'use git in a project'], 'In the project folder run `git init`, then `git add .` and `git commit -m "first commit"`.'],
  [['clone a repository', 'download a github repo', 'clone a repo'], 'Run `git clone https://github.com/user/repo`.'],
  [['commit my changes', 'make a commit', 'save my work in git'], 'Run `git add file` (or `git add .`) and then `git commit -m "what changed"`. Or use `gitui`.'],
  [['push to github', 'upload my code to github', 'push my changes'], 'Run `git push`. The first time on a new branch: `git push -u origin branch-name`.'],
  [['pull changes', 'get the latest code', 'update my repo'], 'Run `git pull`.'],
  [['make a new branch', 'create a branch'], 'Run `git switch -c branch-name`.'],
  [['switch branches', 'change branch'], 'Run `git switch branch-name`.'],
  [['see what changed in git', 'see my changes'], 'Run `git status` to list changed files and `git diff` to see the changes — or `gitui` for both.'],
  [['undo my last commit', 'undo a commit'], 'Run `git reset --soft HEAD~1` to undo it but keep the changes.'],
  [['see git history', 'see old commits'], 'Run `git log --oneline`.'],
  [['make a pull request', 'open a pull request'], 'Push your branch, then run `gh pr create` — or in `gitui`, press P.'],

  // --- coding ---------------------------------------------------------------------------
  [['run a python file', 'run python code', 'run a python script'], 'Run `python3 file.py`. In `edit`, ^T runs the file you’re editing.'],
  [['install a python package', 'use pip'], 'Run `pip3 install name`, for example `pip3 install requests`.'],
  [['start learning to code', 'learn programming', 'learn to code', 'start coding'], 'Pick one language (Python is friendly), follow a beginner tutorial, and build tiny projects — a calculator, a guessing game — every day.'],
  [['learn python'], 'Start with variables, if statements and loops. Write small programs like a number guessing game, and practise a little every day.'],
  [['print something in python', 'print in python'], 'Use `print("Hello!")`.'],
  [['make a loop in python', 'write a for loop in python'], 'Use `for i in range(5):` and indent the lines inside it. That runs them five times.'],
  [['make a variable in python'], 'Write a name, =, and a value: `score = 10`.'],
  [['write an if statement in python'], 'Use `if score > 5:` then indent the code to run; add `else:` for the other case.'],
  [['make a function in python'], 'Use `def greet(name):` and indent the body; call it with `greet("Max")`.'],
  [['get input in python', 'ask the user for input in python'], 'Use `name = input("What is your name? ")`.'],
  [['run javascript', 'run a javascript file', 'run node'], 'Run `node file.js`.'],
  [['install an npm package', 'use npm'], 'Run `npm install name` in your project folder.'],
  [['make a website', 'build a website', 'make a simple website'], 'Make a file called index.html with `<h1>Hello!</h1>` in it and open it in a browser. Then add CSS for style and JavaScript for behaviour.'],
  [['center a div', 'center something in css'], 'On the parent use `display: flex; justify-content: center; align-items: center;`.'],
  [['fix a bug', 'debug my code', 'find a bug'], 'Read the error message first, find the line it points to, and print values around there to see what’s different from what you expect.'],
  [['make a game', 'make a video game', 'start making games'], 'Start small — a guessing game in Python, or Scratch for visual games. Then try a game library like Pygame, or an engine like Godot or Unity.'],
  [['comment code', 'write a comment in code'], 'In Python and shell use `#`; in JavaScript use `//`. In `edit`, M-3 comments a block.'],

  // --- maxshell -------------------------------------------------------------------------
  [['undo in maxshell', 'undo what i typed'], 'At the prompt, Ctrl-Z undoes your last edit. While a command runs, Ctrl-Z pauses it instead.'],
  [['pause a program', 'suspend a program'], 'Press Ctrl-Z. Then `jobs` lists it, `fg` brings it back and `bg` keeps it running in the background.'],
  [['run something in the background'], 'Put `&` at the end: `sleep 60 &`. `jobs` shows it, and `fg` brings it back.'],
  [['free up memory', 'make my mac faster', 'free up ram'], 'Run `cleanup` to quit what isn’t needed, or `cleanup -r` to pick from what uses the most memory.'],
  [['change the colours', 'change the theme', 'change the colors of maxshell'], 'Run `theme` to see them all, then `theme nord` (or any name) to switch.'],
  [['search my history in maxshell'], 'Press Ctrl-R and type any words from the command you want.'],
  [['open the command palette', 'use the palette'], 'Press Ctrl-P — everything maxshell can do, searchable.'],
  [['explain a command', 'understand a command'], 'Type it and press Alt-H, or run `explain \'the command\'`.'],
  [['edit a file', 'open a file in an editor'], 'Run `edit file.txt`. ^O saves and ^X exits.'],
  [['browse my files', 'use the file browser'], 'Run `files` for a Finder-style browser. Press q to leave in that folder.'],
  [['use git in maxshell', 'use gitui'], 'Run `gitui` to stage, diff, commit and push.'],
  [['go back to zsh', 'stop using maxshell as my shell'], 'Run `chsh -s /bin/zsh`, then open a new terminal window.'],
  [['make maxshell my default shell'], 'Run `maxshell --make-default`.'],
  [['add an alias in maxshell'], 'Put `alias ll=\'ls -l\'` in ~/.maxshellrc and it loads every time maxshell starts.'],
  [['jump to a folder', 'go to a folder quickly'], 'Use `j` with part of its name, like `j proj`. It learns the folders you visit.'],
  [['save a command for later', 'save a snippet'], 'Press Alt-S to save the line as a snippet, and `snip` to bring it back.'],
  [['see what my computer is doing', 'see a dashboard'], 'Run `top` for processes, or `dash` for a live dashboard.'],
  [['quit maxshell', 'exit maxshell', 'close the shell'], 'Type `exit` or press Ctrl-D on an empty line.'],
  [['bookmark a folder'], 'Run `mark` in the folder, and `go` to jump back to it later.'],

  // --- making things --------------------------------------------------------------------
  [['make a paperclip', 'bend a paperclip'], 'Take a thin, stiff wire about 10 cm long. Bend it into a long U, then bend the end back inside that U to make a smaller U, and once more — three loops nested inside each other, like a flat spiral.'],
  [['make a paper airplane', 'fold a paper airplane'], 'Fold a sheet in half lengthwise and open it. Fold the top corners to the middle line, fold the new slanted edges to the middle again, fold the plane in half, then fold each side down to make the wings.'],
  [['make a paper boat', 'fold a paper boat'], 'Fold a sheet in half top to bottom, fold the top corners to the middle, fold the bottom strips up on both sides, open it into a square, fold that into a triangle, then pull the sides apart into a boat.'],
  [['make an origami crane', 'fold a paper crane'], 'Start with a square sheet folded into a “bird base”, fold the edges in to make it narrow, fold up the neck and tail, then pull the wings down. Searching for a diagram helps a lot the first time!'],
  [['make a paper hat'], 'Fold a large sheet in half, fold the top corners to the middle, then fold the bottom strips up on each side.'],
  [['make slime'], 'Mix about 120 ml of white glue with a spoon of baking soda, then add contact lens solution a little at a time and knead until it stops being sticky.'],
  [['make a friendship bracelet'], 'Cut a few colourful threads, knot them together at one end, tape it down and braid or knot them in a pattern until it fits your wrist.'],
  [['tie my shoes', 'tie shoelaces', 'tie a shoe'], 'Cross the laces and pull one under to make a knot. Make a loop with one lace, wrap the other around it, and push it through the hole to make a second loop. Pull both loops tight.'],
  [['tie a tie'], 'Drape it with the wide end longer, cross it over the thin end, wrap it around once, bring it up through the neck loop and down through the knot in front, then tighten.'],
  [['draw a cat', 'draw a simple cat'], 'Draw a circle for the head and a bigger oval for the body, add two triangle ears, eyes, a small nose and whiskers, then a long curvy tail.'],
  [['draw a person'], 'Start with a circle for the head, an oval for the body, and lines for arms and legs. Then add details like hair, clothes and a face.'],
  [['get better at drawing', 'learn to draw'], 'Draw a little every day, copy simple shapes first, and draw from real objects around you.'],
  [['build a sandcastle'], 'Use wet sand — pack it into a bucket, flip it over, and tap it out. Stack towers, then carve windows and walls with a spoon.'],

  // --- food -----------------------------------------------------------------------------
  [['boil an egg', 'make a boiled egg', 'hard boil an egg'], 'Put the egg in boiling water: about 6 minutes for a soft yolk, 10 minutes for hard. Then cool it in cold water before peeling.'],
  [['make scrambled eggs', 'scramble eggs'], 'Whisk two eggs with a pinch of salt, melt butter in a pan on low heat, pour them in and stir slowly until just set.'],
  [['make pancakes'], 'Mix 1 cup flour, 1 egg, 1 cup milk, 1 tablespoon sugar and 2 teaspoons baking powder. Cook scoops in a hot buttered pan, flipping when bubbles appear.'],
  [['make tea', 'make a cup of tea'], 'Boil water, pour it over a tea bag, wait 3 to 5 minutes, remove the bag, and add milk or honey if you like.'],
  [['make hot chocolate'], 'Warm a cup of milk, stir in two spoons of cocoa powder and a spoon of sugar (or a chocolate mix), and serve.'],
  [['make a sandwich'], 'Take two slices of bread, spread butter or sauce, add your fillings — cheese, ham, lettuce, tomato — and press them together.'],
  [['make popcorn'], 'Heat a little oil in a pot with a lid, add kernels in one layer, cover, and shake while they pop. Take it off the heat when popping slows.'],
  [['cook pasta', 'make pasta'], 'Boil salted water, add pasta and stir, cook for the time on the packet (usually 8–12 minutes), then drain.'],
  [['make rice', 'cook rice'], 'Rinse 1 cup of rice, add 2 cups of water and a pinch of salt, bring to a boil, then cover and simmer on low for about 15 minutes.'],
  [['bake cookies', 'make cookies'], 'Mix butter and sugar, add an egg, then flour, baking soda and chocolate chips. Scoop onto a tray and bake at 180 °C (350 °F) for about 10 minutes.'],
  [['make a smoothie'], 'Blend a banana, a handful of frozen fruit, a cup of milk or yogurt, and a spoon of honey until smooth.'],
  [['make lemonade'], 'Mix the juice of 4 lemons with 4 cups of water and about half a cup of sugar. Stir until dissolved and add ice.'],

  // --- school and life --------------------------------------------------------------------
  [['study for a test', 'study better', 'prepare for an exam'], 'Study in short sessions with breaks, test yourself instead of just re-reading, and sleep well the night before.'],
  [['focus', 'stay focused', 'concentrate'], 'Put your phone away, work for 25 minutes, take a 5-minute break, and repeat. Start with the easiest small step.'],
  [['write an essay', 'start an essay'], 'Pick one main idea, plan three points that support it, then write an introduction, a paragraph for each point, and a conclusion.'],
  [['take good notes', 'take notes'], 'Write key ideas in your own words, use headings and bullet points, and review them the same day.'],
  [['write an email', 'write a good email'], 'Give it a clear subject, greet the person, say what you need in the first line or two, keep it short, and end with a thank you.'],
  [['fall asleep', 'fall asleep faster', 'sleep better'], 'Put screens away 30 minutes before bed, keep the room dark and cool, and go to bed at the same time every night.'],
  [['wake up early'], 'Go to bed earlier, put your alarm across the room, and open the curtains as soon as you’re up.'],
  [['make friends', 'make new friends'], 'Join clubs or activities you enjoy, ask people questions about themselves, and say yes when they invite you.'],
  [['be more confident'], 'Practise small brave things, stand up straight, prepare for what makes you nervous, and remember everyone makes mistakes.'],
  [['stop procrastinating'], 'Make the first step tiny, set a timer for 10 minutes, and start. Getting going is the hardest part.'],
  [['save money'], 'Decide on an amount to save first, track what you spend, and wait a day before buying things you don’t need.'],
  [['make a strong password', 'make a good password'], 'Use a long passphrase of several random words, never reuse it, and keep it in a password manager.'],
  [['learn a new language'], 'Practise a little every day with an app or a book, learn the most common words first, and talk with people who speak it.'],
  [['memorize something', 'remember things better'], 'Repeat it several times over a few days, test yourself, and connect it to something you already know.'],
  [['calm down', 'relax', 'deal with stress'], 'Breathe in slowly for 4 seconds, hold for 4, breathe out for 6, and repeat a few times. A short walk helps too.'],
  [['wash my hands', 'wash hands properly'], 'Wet your hands, lather with soap for 20 seconds (including between fingers and under nails), rinse and dry.'],
  [['plant a seed', 'grow a plant'], 'Fill a pot with soil, push the seed in about twice as deep as it is big, water it, and keep it somewhere bright and warm.'],
  [['take care of a plant'], 'Water it when the top of the soil is dry, give it light, and don’t let it sit in water.'],
  [['make my bed'], 'Straighten the bottom sheet, pull the covers up flat, fold the top over, and put the pillows at the head.'],
  [['ride a bike', 'learn to ride a bike'], 'Start on a gentle grassy slope, push off with both feet, look ahead (not down), and keep pedalling — speed makes balancing easier.'],
  [['swim', 'learn to swim'], 'Start in shallow water with a teacher, practise floating and kicking, then add arm strokes and breathing.'],
  [['do a push up', 'do push ups'], 'Put your hands under your shoulders, keep your body straight, lower your chest toward the floor, then push back up.'],
  [['juggle', 'learn to juggle'], 'Start with one ball tossed from hand to hand in an arc, then two, then three — throw the next ball when the last one peaks.'],
  [['solve a rubiks cube', 'solve a rubik’s cube'], 'Learn the beginner method: make a white cross, finish the white layer, then the middle layer, then the yellow cross, and finally place the yellow corners.'],
  [['play chess', 'learn chess'], 'Learn how each piece moves, try to control the centre, get your knights and bishops out early, and protect your king by castling.'],
  [['get better at a video game'], 'Practise the basics, watch how good players play, learn from each loss, and take breaks when you’re frustrated.'],
  [['write a story'], 'Start with a character who wants something, add a problem that gets in the way, and end with how they solve it (or don’t).'],
  [['make a presentation'], 'Plan three main points, put one idea per slide with big text and pictures, and practise saying it out loud.'],
];
